"""Centralized error code taxonomy for analysis pipeline."""

ERR_LLM_DISABLED = "ERR_LLM_DISABLED"
ERR_LLM_RATE_LIMIT = "ERR_LLM_RATE_LIMIT"
ERR_LLM_AUTH = "ERR_LLM_AUTH"
ERR_LLM_PROVIDER = "ERR_LLM_PROVIDER"
ERR_PROVIDER_NOT_SUPPORTED = "ERR_PROVIDER_NOT_SUPPORTED"

ERR_RAG_UNAVAILABLE = "ERR_RAG_UNAVAILABLE"

ERR_PDF_LAYOUT_OVERFLOW = "ERR_PDF_LAYOUT_OVERFLOW"
ERR_PDF_FONT = "ERR_PDF_FONT"
ERR_PDF_UNKNOWN = "ERR_PDF_UNKNOWN"
